home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView, name='home'),
    path('faq/', views.FaqView, name='faq'),
    path('about/', views.AboutView, name='about'),
    path('plans/', views.PlanView, name='plan'),
    path('contact/', views.ContactView, name='contact'),
    path('blog/', views.BlogView, name='blog'),
    path('blog/read/<int:id>/', views.BlogDetailsView, name='blog_details'),
    path('blog/search-result/', views.SearchBlogView, name='search_blog'),
    
]

ptc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Plan(models.Model):
    title = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    description = models.TextField()
    period = models.PositiveIntegerField()
    ad_limit = models.PositiveIntegerField()
    reffer_bonus = models.CharField(default='N/A', max_length=100)
    tag= models.CharField(max_length=100, null=True, blank=True)
    
    
    def __str__(self):
        return self.title
    
    def get_price(self):
        return int(self.price)
    
    
class Feature(models.Model):
    icon = models.ImageField(upload_to='uploads/features/', blank=True, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    
    def __str__(self):
        return self.title
    
    
class FAQ(models.Model):
    question = models.TextField()
    answer = models.TextField()
    
    def __str__(self):
        return self.question
    
    
class CompanyProfile(models.Model):
    
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    location = models.CharField(max_length=200)
    facebook = models.CharField(max_length=200)    
    twitter = models.CharField(max_length=200)
    instagram = models.CharField(max_length=200)
    linkedin = models.CharField(max_length=200)
    
    class Meta:
        verbose_name_plural = 'Company Profile Info'
    
    def __str__(self):
        return f'{self.email} - {self.phone}'
    


    
    
class Blog(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    icon = models.ImageField(upload_to='blogs/', null=True, blank=True)
    author = models.CharField(max_length=100)
    tag = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    

    
    
class Testmonial(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=255)
    icon = models.ImageField(upload_to='testmonial/', null=True, blank=True)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import *

# Create your views here.

def HomeView(request):
    plan = Plan.objects.all()
    feature = Feature.objects.all()
    latest_blogs = Blog.objects.order_by('-created_at')[:3]
    testmonial = Testmonial.objects.all()
    context = {
        'plan':plan,
        'feature':feature,
        'latest_blogs':latest_blogs,
        'testmonial':testmonial,
    }
    return render(request, 'home/index.html', context)


def FaqView(request):
    faq = FAQ.objects.all()
    context = {
        'faq':faq
    }
    return render(request, 'home/FAQ.html', context)


def AboutView(request):
    feature = Feature.objects.all()
    testmonial = Testmonial.objects.all()
    context = {
        'feature':feature,
        'testmonial':testmonial,
    }
    return render(request, 'home/about.html', context)


def BlogView(request):
    list_blogs = Blog.objects.all()
    latest_blogs = list_blogs.order_by('-created_at')[:5]
    
    paginator = Paginator(list_blogs, 3)
    page_number = request.GET.get('page')
    
    try:
        blogs = paginator.page(page_number)
    except PageNotAnInteger:
        blogs = paginator.page(1)  
    except EmptyPage:
        blogs= paginator.page(paginator.num_pages)
    
    context = {
        'blogs':blogs,
        'latest_blogs':latest_blogs,
    }
    return render(request, 'home/blog.html', context)

def SearchBlogView(request):
    latest_blogs = Blog.objects.order_by('-created_at')[:3]
    keyword = request.GET.get('search')
    
    if keyword:
        list_results = Blog.objects.filter(title__icontains=keyword) | Blog.objects.filter(description__icontains=keyword)
    elif keyword == '':
        list_results = Blog.objects.all()
    else:
        list_results = Blog.objects.none()
    
        
    paginator = Paginator(list_results, 3)
    page_number = request.GET.get('page')
    
    try:
        blogs = paginator.page(page_number)
    except PageNotAnInteger:
        blogs = paginator.page(1)  
    except EmptyPage:
        blogs= paginator.page(paginator.num_pages)

    
    context = {
        'keyword':keyword,
        'blogs':blogs,
        'latest_blogs':latest_blogs
    }
    
    return render(request, 'home/search_result.html', context)

def ContactView(request):
    return render(request, 'home/contact.html')

def PlanView(request):
    plan = Plan.objects.all()
    context = {
        'plan':plan
    }
    return render(request, 'home/plan.html', context)


def BlogDetailsView(request, blog_id):
    pass

templates/home/FAQ.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Blog {% endblock %}

{% block content %}

<section class="banner-section">
    <div class="container">
       <div class="row">
          <div class="col text-center">
             <h3>Frequently Asked Questions</h3>
             <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                   <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
                   <li class="breadcrumb-item active" aria-current="page">Frequently Asked Questions</li>
                </ol>
             </nav>
          </div>
       </div>
    </div>
 </section>

 <section class="faq-section faq-page">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-10">
          <div class="accordion" id="accordionExample">
            {% for faq in faq %}
                <div class="accordion-item">
                    <h5 class="accordion-header" id="heading{{ forloop.counter }}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                            {{ faq.question }}
                        </button>
                    </h5>
                    <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            {{ faq.answer }}
                        </div>
                    </div>
                </div>
            {% endfor %}
          </div>        
        </div>
      </div>
    </div>
  </section>

 {% endblock %}

templates/home/blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Blog {% endblock %}

{% block content %}

<section class="banner-section">
    <div class="container">
       <div class="row">
          <div class="col text-center">
             <h3>Blog</h3>
             <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                   <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
                   <li class="breadcrumb-item active" aria-current="page">Blog</li>
                </ol>
             </nav>
          </div>
       </div>
    </div>
 </section>


 <section class="blog-page blog-details">
    <div class="container">
      <div class="row g-lg-5">
        <div class="col-lg-8">
         
          {% for data in blogs %}
          <div class="blog-box">
            <div class="img-box">
              <img src="{{ data.images.url }}" class="img-fluid" alt="blog img">
            </div>
            <div class="text-box">
              <div class="date-author flex-wrap">
                <div class="d-flex">
                  <span>
                    <i class="fal fa-clock" aria-hidden="true"></i> {{data.created_at|date:"F d, Y"}} </span>
                  <span class="ms-3">
                    <i class="fal fa-user-circle" aria-hidden="true"></i> {{data.author}} </span>
                </div>
                <span>
                  <i class="fal fa-tags" aria-hidden="true"></i> {{data.tag}} </span>
              </div>
              <h5 class="title">{{data.title}}</h5>
              <p></p>
              <p>{{data.description|truncatewords:40}}</p>
              <a href="{% url 'home:blog_details' data.id %}" class="btn-custom mt-3">Read More</a>
            </div>
          </div>
          {% endfor %}
          <div class="row py-5 mt-5">
            <nav id="pagination">
              <ul class="pagination wow fadeInUp justify-content-sm-center justify-content-start flex-wrap" data-wow-duration="1s" data-wow-delay="0.35s">
                {% if blogs.has_previous %}
                  <li class="page-item">
                    <a href="?page={{ blogs.previous_page_number }}" class="page-link" aria-label="Previous">
                      <span aria-hidden="true">«</span>
                    </a>
                  </li>
                
                {% endif %}
                
                {% for num in blogs.paginator.page_range %}
                  {% if blogs.number == num %}
                    <li class="page-item active">
                      <a href="#" class="page-link">{{ num }} <span class="sr-only">(current)</span></a>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                
                {% if blogs.has_next %}
                  <li class="page-item">
                    <a href="?page={{ blogs.next_page_number }}" class="page-link" aria-label="Next">
                      <span aria-hidden="true">»</span>
                    </a>
                  </li>
               
                {% endif %}
              </ul>
            </nav>
          </div>
          
          <!-- <div id="shareBlock">Share now</div> -->
        </div>
        <div class="col-lg-4">
          <div class="side-bar">
            <div class="side-box">
              <form action="{% url 'home:search_blog' %}" method="GET">
                <input type="hidden" name="_token" value="VD3fFSSPU1RIUedv0PZDy17ZF3NxvV9hpNZI6M2i">
                <h4>Search here</h4>
                <div class="input-group">
                  <input type="text" class="form-control" name="search" id="search" placeholder="search here...">
                  <button type="submit">
                    <i class="fal fa-search" aria-hidden="true"></i>
                  </button>
                </div>
              </form>
            </div>
            <div class="side-box">
              <h4>Recent Posts</h4>

              {% for data in latest_blogs %}
              <div class="blog-box">
                <div class="img-box">
                  <a href="{% url 'home:blog_details' data.id %}">
                    <img class="img-fluid" src="{{data.images.url}}" alt="related blog img">
                  </a>
                </div>
                <div class="text-box">
                  <span class="date">{{data.created_at|date:"F d, Y"}}</span>
                  <a href="https://ptc-pro.bugfinder.net/blog-details/blockchain-com-closes-crypto-custody-for-russians-amid-eu-sanctions/7" class="title">{{data.title|truncatewords:6}} </a>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  
{% endblock %}

templates/home/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Contact {% endblock %}

{% block content %}
<section class="banner-section">
    <div class="container">
       <div class="row">
          <div class="col text-center">
             <h3>Contact Us</h3>
             <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                   <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Home</a></li>
                   <li class="breadcrumb-item active" aria-current="page">Contact Us</li>
                </ol>
             </nav>
          </div>
       </div>
    </div>
 </section>


 <div class="contact-section">
    <div class="container">
      <div class="info-wrapper">
        <div class="row g-lg-5 g-4">
          <div class="col-lg-4">
            <div class="info-box">
              <div class="icon">
                <img src="{% static 'assets/themes/linen/images/icon/location.png' %}" alt="location img">
              </div>
              <div class="text">
                <h4>Location</h4>
                <p>{{company_profile.location}}</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="info-box">
              <div class="icon">
                <img src="{% static 'assets/themes/linen/images/icon/email.png' %}" alt="email img">
              </div>
              <div class="text">
                <h4>Email</h4>
                <p>{{company_profile.email}}</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="info-box">
              <div class="icon">
                <img src="{% static 'assets/themes/linen/images/icon/phone-call.png' %}" alt="phone img">
              </div>
              <div class="text">
                <h4>Phone</h4>
                <p>{{company_profile.phone}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <div class="img-box">
            <img src="https://ptc-pro.bugfinder.net/assets/uploads/content/63c3d37c8728f1673778044.png" alt="contact img" class="img-fluid">
          </div>
        </div>
        <div class="col-lg-6">
          <h3>Just Drop Us A Line.</h3>
          <p class="mb-4">Give us a call or drop by anytime, we will be happy to answer your questions.</p>
          <form action="https://ptc-pro.bugfinder.net/contact" method="POST">
            <input type="hidden" name="_token" value="HN5JSh2s5acKDWdFxiFhqgrSdOzAJqEjaA4P4ZhN">
            <div class="row g-3">
              <div class="input-box col-md-6">
                <input class="form-control" type="text" name="name" value="" placeholder="Full name">
              </div>
              <div class="input-box col-md-6">
                <input class="form-control" type="email" name="email" value="" placeholder="Email address">
              </div>
              <div class="input-box col-12">
                <input type="text" name="subject" value="" placeholder="Subject" class="form-control">
              </div>
              <div class="input-box col-12">
                <textarea class="form-control" cols="30" rows="3" name="message" placeholder="Your message"></textarea>
              </div>
              <div class="input-box col-12">
                <button type="submit" class="btn-custom">submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}


<section class="home-section">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-lg-6">
                <div class="text-box">
                    <h3>Introducing Onshape Simulation</h3>
                    <h1>Enlarge Your Network And Get More Commissions</h1>
                    <p><span>New cloud-native simulation technology delivers fast, easy, and accurate mechanical guidance to designers.</span></p>
                    <a href="https://codecanyon.net/user/bug-finder/portfolio" class="btn-custom mt-4" target="_blank">
                        Learn More                        </a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="img-box">
                    <img src="{% static 'assets/uploads/content/63c3961d658811673762333.png' %}" class="img-fluid" alt="hero banner">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ABOUT-US -->
<section class="about-section">
    <div class="container">
       <div class="row align-items-center">
          <div class="col-lg-6">
             <div class="img-box" data-aos="fade-right" data-aos-duration="1000" data-aos-anchor-placement="center-bottom">
                <img src="{% static 'assets/uploads/content/63c3966f28dbc1673762415.png' %}" class="img-fluid" alt="ABOUT US">
             </div>
          </div>
          <div class="col-lg-6">
             <div class="text-box" data-aos="fade-left" data-aos-duration="1000" data-aos-anchor-placement="center-bottom">
                <div class="header-text mb-5">
                   <h5>ABOUT US</h5>
                   <h2>We Use Digital Technology To Improve The Physical World</h2>
                </div>
                <p></p><p><span>A cryptocurrency, crypto-currency, or crypto is a collection of binary data which is designed to work as a medium of exchange. Individual coin ownership records are stored in a ledger, which is a computerized database using strong cryptography to secure transaction records, to control the creation of additional coins, and to verify the transfer of coin ownership. Try to save</span><br></p><p></p>

                <a href="https://bugfinder.net/" class="btn-custom mt-4">Know More</a>
             </div>
          </div>
       </div>
    </div>
 </section>
<!-- /ABOUT-US -->

<!-- Plan -->>
<section class="pricing-section">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="header-text text-center">
            <h5>OUR PRICING</h5>
            <h2>Fair Pricng For You</h2>
          </div>
        </div>
      </div>

        <div class="row g-4 g-lg-5">
        {% for plan in plan %}
        <div class="col-lg-4 col-md-6">
          <div class="pricing-box" data-aos="fade-up" data-aos-duration="1000" data-aos-anchor-placement="center-bottom">
            <h4>{{plan.title}}</h4>
            <h1>{{plan.price}}</h1>
            <p>{{plan.description}}</p>
            <ul>
              <li>
                <i class="fal fa-check-circle text-success"></i>Period : {{plan.period}} Days
              </li>
              <li>
                <i class="fal fa-check-circle text-success"></i>Daily Ad Limit : {{plan.ad_limit}} PTC
              </li>
              <li>
                <i class="fal fa-{% if plan.reffer_bonus == 'N/A' %}times{% else %}check{% endif %}-circle text-{% if plan.reffer_bonus == 'N/A' %}danger{% else %}success{% endif %}"></i> Referral Bonus : Up to {{plan.reffer_bonus}} level
              </li>
            </ul>
            <button class="btn-custom w-100 purchaseNow" data-bs-toggle="modal" data-bs-target="#planModal" data-price="00" data-resource="{&quot;id&quot;:2,&quot;plan_id&quot;:2,&quot;language_id&quot;:1,&quot;name&quot;:&quot;Free&quot;,&quot;tag&quot;:&quot;Free&quot;,&quot;short_title&quot;:&quot;The perfect way to get started and get used to our tools&quot;,&quot;created_at&quot;:&quot;2023-01-17T07:20:36.000000Z&quot;,&quot;updated_at&quot;:&quot;2023-01-18T03:44:57.000000Z&quot;}"> Purchase Plan </button>
            {% if plan.tag %}
            <span class="feature">{{plan.tag}}</span>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    
        </div>
      </div>
    </div>
  </section>
  <!-- Plan End -->>
  <!--Plan Modal -->
  <div id="planModal" class="modal fade modal-with-form" data-bs-backdrop="static" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <!-- Modal content-->
      <div class="modal-content form-block">
        <div class="modal-header">
          <h4 class="modal-title">Purchase Plan</h4>
          <button type="button" class="close-btn" data-bs-dismiss="modal" aria-label="Close">
            <i class="fal fa-times"></i>
          </button>
        </div>
        <form class="login-form" id="invest-form" action="https://no31VC7Jjjy1.net/user/purchase/plan" method="post">
          <input type="hidden" name="_token" value="b8DYK1jwpzwm43U66ywxRoIYzKAVFh1szEwuLKzV">
          <div class="modal-body">
            <div class="form-group">
              <h5 class="text-center py-2">Please at first login to your account to purchase plan.</h5>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn-custom close-btn" data-bs-dismiss="modal">Close</button>
            <a href="https://no31VC7Jjjy1.net/login" class="btn-custom">Login</a>
          </div>
        </form>
      </div>
    </div>
  </div>




<section class="feature-section">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="header-text text-center">
                            <h5>FEATUERS</h5>
                            <h2>Our Featuers</h2>
                        </div>
                    </div>
                </div>
                <div class="row g-4">

                    {% for feature in feature %}
                    <div class="col-md-6 col-lg-4">
                        <div class="feature-box" data-aos="fade-up" data-aos-duration="1000" data-aos-anchor-placement="center-bottom">
                            <div class="icon-box">
                                {% if feature.icon %}
                                <img src="{{ feature.image.url }}" alt="feature img">
                                {% else %}
                                <img src="{% static 'assets/uploads/content/63c3974ae308b1673762634.gif' %}" alt="feature img">
                                {% endif %}
                            </div>
                            <h4>{{feature.title}}</h4>
                            <p>{{feature.description}}</p>
                        </div>
                    </div>
                    {% endfor %}
                
                </div>
            </div>
        </section>
            <!-- commission section of deposit -->
<!-- end commission section of deposit -->
<style>
            .testimonial-section .testimonial-wrapper {
                border-radius: 20px;
                background: url(assets/uploads/content/63c39f356e0031673764661.jpg);
                background-size: cover;
                background-position: center;
            }
</style>
<!-- TESTIMONIAL -->
<section class="testimonial-section">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="header-text text-center">
            <h5>TESTIMONIALS</h5>
            <h2>Trusted By Millions Of Users Worldwide</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="testimonial-wrapper">
            <div class="testimonials owl-carousel">
 
             {% for data in testmonial %}
              <div class="review-box" data-aos="fade-up" data-aos-duration="1000" data-aos-anchor-placement="center-bottom">
                <p>{{data.comment}}</p>
                <div class="top">
                  {% if data.icon %}
                  <img src="{{ data.icon.url }}" alt="testimonial img">
                  {% endif %}
                  <div>
                    <h4>{{data.name}}</h4>
                    <span class="title">{{data.designation}}</span>
                  </div>
                </div>
                <div class="quote">
                  <i class="fal fa-quote-left"></i>
                </div>
              </div>
             {% endfor %}
             
              
         
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<!-- /TESTIMONIAL -->
        
<!-- commission section of plan purchase -->
<!-- end commission section of plan purchase -->
<!-- BLOG -->
<section class="blog-section">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="header-text text-center">
            <h5>OUR BLOGS</h5>
            <h2>Latest News &amp; Articles</h2>
          </div>
        </div>
      </div>
      <div class="row g-4 g-lg-5">
        {% for data in latest_blogs %}
        <div class="col-lg-4 col-md-6">
          <div class="blog-box" data-aos="fade-up" data-aos-duration="1000" data-aos-anchor-placement="center-bottom">
            <div class="img-box">
              <img src="{{ data.icon.url }}" class="img-fluid" alt="blog thumb" style="width: 400px; height: 200px;">
            </div>
            <div class="text-box">
              <div class="date-author">
                <span>
                  <i class="fal fa-calendar-alt"></i> {{data.created_at|date:"F d, Y"}} </span>
                <span>
                  <i class="fal fa-user-circle"></i> {{data.author}} </span>
              </div>
              <h5 class="title"> {{data.title}} <p></p>
                <a href="{% url 'home:blog_details' data.id %}" class="btn-custom"> Read More </a>
              </h5>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
<!-- /BLOG -->

{% endblock %}

templates/home/search_result.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Blog {% endblock %}

{% block content %}

<section class="banner-section">
    <div class="container">
       <div class="row">
          <div class="col text-center">
             <h3>Search results...</h3>
             <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center">
                   <li class="breadcrumb-item"><a href="https://ptc-pro.bugfinder.net">Home</a></li>
                   <li class="breadcrumb-item active" aria-current="page">Blog</li>
                </ol>
             </nav>
          </div>
       </div>
    </div>
 </section>


 <section class="blog-page blog-details">
    <div class="container">
        {% if blogs %}
      <div class="row g-lg-5">
        <div class="col-lg-8">
          {% for data in blogs %}
          <div class="blog-box">
            <div class="img-box">
              <img src="{{ data.images.url }}" class="img-fluid" alt="blog img">
            </div>
            <div class="text-box">
              <div class="date-author flex-wrap">
                <div class="d-flex">
                  <span>
                    <i class="fal fa-clock" aria-hidden="true"></i> {{data.created_at|date:"F d, Y"}} </span>
                  <span class="ms-3">
                    <i class="fal fa-user-circle" aria-hidden="true"></i> {{data.author}} </span>
                </div>
                <span>
                  <i class="fal fa-tags" aria-hidden="true"></i> {{data.tag}} </span>
              </div>
              <h5 class="title">{{data.title}}</h5>
              <p></p>
              <p>{{data.description|truncatewords:40}}</p>
              <a href="{% url 'home:blog_details' data.id %}" class="btn-custom mt-3">Read More</a>
            </div>
          </div>
          {% endfor %}
          <div class="row py-5 mt-5">
            <nav id="pagination">
              <ul class="pagination wow fadeInUp justify-content-sm-center justify-content-start flex-wrap" data-wow-duration="1s" data-wow-delay="0.35s">
                {% if blogs.has_previous %}
                  <li class="page-item">
                    <a href="?page={{ blogs.previous_page_number }}" class="page-link" aria-label="Previous">
                      <span aria-hidden="true">«</span>
                    </a>
                  </li>
                
                {% endif %}
                
                {% for num in blogs.paginator.page_range %}
                  {% if blogs.number == num %}
                    <li class="page-item active">
                      <a href="#" class="page-link">{{ num }} <span class="sr-only">(current)</span></a>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                
                {% if blogs.has_next %}
                  <li class="page-item">
                    <a href="?page={{ blogs.next_page_number }}" class="page-link" aria-label="Next">
                      <span aria-hidden="true">»</span>
                    </a>
                  </li>
               
                {% endif %}
              </ul>
            </nav>
          </div>
          
          <!-- <div id="shareBlock">Share now</div> -->
        </div>
        <div class="col-lg-4">
          <div class="side-bar">
            <div class="side-box">
              <form action="{% url 'home:search_blog' %}" method="GET">
                <input type="hidden" name="_token" value="VD3fFSSPU1RIUedv0PZDy17ZF3NxvV9hpNZI6M2i">
                <h4>Search here</h4>
                <div class="input-group">
                  <input type="text" class="form-control" name="search" id="search" placeholder="Search here", value="{{keyword}}">
                  <button type="submit">
                    <i class="fal fa-search" aria-hidden="true"></i>
                  </button>
                </div>
              </form>
            </div>
            <div class="side-box">
              <h4>Recent Posts</h4>

              {% for data in latest_blogs %}
              <div class="blog-box">
                <div class="img-box">
                  <a href="{% url 'home:blog_details' data.id %}">
                    <img class="img-fluid" src="{{data.images.url}}" alt="related blog img">
                  </a>
                </div>
                <div class="text-box">
                  <span class="date">{{data.created_at|date:"F d, Y"}}</span>
                  <a href="https://ptc-pro.bugfinder.net/blog-details/blockchain-com-closes-crypto-custody-for-russians-amid-eu-sanctions/7" class="title">{{data.title|truncatewords:6}} </a>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
      {% else %}
      <h4>Oops, no result found..!</h4>
      {% endif%}
    </div>
  </section>

  
{% endblock %}