account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView, name='register'),
    path('login/', views.LoginView, name='login'),
    path('activate/<uidb64>/<token>/', views.ActivateView, name='activate'),
    path('logout/', views.LogoutView, name='logout'),
    path('forget_password/', views.ForgetPasswordView, name='forget_password'),
    path('reset_password/<uidb64>/<token>/', views.ResetPasswordValidateView, name='reset_password_validate'),
    path('reset_password_process/', views.ResetPasswordView, name='reset_password'),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView, name='home'),
    path('faq/', views.FaqView, name='faq'),
    path('about/', views.AboutView, name='about'),
    path('plans/', views.PlanView, name='plan'),
    path('contact/', views.ContactView, name='contact'),
    path('blog/', views.BlogView, name='blog'),
    path('blog/read/<int:id>/', views.BlogDetailsView, name='blog_details'),
    path('blog/search-result/', views.SearchBlogView, name='search_blog'),
    
]

ptc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/alerts.html
{% if form.email.errors %}

	{% for message in form.email.errors %}
	<div id="message" class="container">
		<div class="alert alert-danger" role="alert">
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
		{{ message }}

		</div>
	</div>
	{% endfor %}

{% endif %}




{% if form.non_field_errors %}

	{% for message in form.non_field_errors %}
	<div id="message" class="container">
		<div class="alert alert-danger text-center" role="alert">
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
		{{ message }}

		</div>
	</div>
	{% endfor %}

{% endif %}


{% if messages %}

	{% for message in messages %}

	<div id="message" class="container" style="padding-top: 10px;">
		<div class="alert alert-success" role="alert">
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
		{{ message }}

		</div>
	</div>
	{% endfor %}

{% endif %}


<script>
    // Set the timeout in milliseconds (e.g., 5000ms = 5 seconds)
    setTimeout(function() {
        var messages = document.querySelectorAll('#message .alert');
        messages.forEach(function(message) {
            message.style.transition = "opacity 0.5s ease";  // Optional: Adds fade out effect
            message.style.opacity = "0";  // Fade out

            // Remove the message from the DOM after the fade out
            setTimeout(function() {
                message.remove();
            }, 500);  // Wait for fade out to complete
        });
    }, 5000);  // The delay before the alert disappears (5000ms = 5 seconds)
</script>

templates/includes/footer.html
{% load static %} 
<footer class="footer-section" id="subscribe">
    <div class="container">
      <div class="row gy-5 gy-lg-0">
        <div class="col-lg-3 col-md-6">
          <div class="footer-box">
            <a class="navbar-brand" href="https://no31VC7Jjjy1.net">
              <img src="{% static 'assets/uploads/logo/admin-logo.png' %}" alt="footer img">
            </a>
            <p class="company-bio"> We are a award winning mulitnational company. We believe quality and standard worldwide consider. </p>
            <div class="social-links">
              <a href="{{ company_profile.facebook }}" target="_blank">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="{{ company_profile.twitter }}" target="_blank">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="{{ company_profile.linkedin }}" target="_blank">
                <i class="fab fa-linkedin-in"></i>
              </a>
              <a href="{{ company_profile.instagram }}" target="_blank">
                <i class="fab fa-instagram"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-box">
            <h4>Quick Links</h4>
            <ul>
              <li>
                <a href="{% url 'home:home' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'home:about' %}">About us</a>
              </li>
              <li>
                <a href="{% url 'home:plan' %}">Plan</a>
              </li>
              <li>
                <a href="{% url 'home:blog' %}">Blogs</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-box">
            <h4>Our Services</h4>
            <ul>
              <li>
                <a href="{% url 'home:contact' %}">Contact</a>
              </li>
              <li>
                <a href="{% url 'home:faq' %}">FAQ</a>
              </li>
              <li>
                <a href="https://no31VC7Jjjy1.net/terms-amp-conditions/33">Terms &amp; Conditions</a>
              </li>
              <li>
                <a href="https://no31VC7Jjjy1.net/privacy-policy/34">Privacy Policy</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 col-md-6">
          <div class="footer-box">
            <h4>Newsletter</h4>
            <p>Get our offers &amp; news in your inbox</p>
            <div class="news-letter">
              <form action="https://no31VC7Jjjy1.net/subscribe" method="post">
                <input type="hidden" name="_token" value="b8DYK1jwpzwm43U66ywxRoIYzKAVFh1szEwuLKzV">
                <div>
                  <input type="email" name="email" value="" placeholder="Email Address" class="form-control">
                  <button type="submit" class="btn-custom">
                    <i class="fad fa-paper-plane"></i>
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="footer-bottom">
        <div class="row">
          <div class="col-md-6">
            <p class="copyright"> Copyright © 2024 <a href="https://no31VC7Jjjy1.net">NOoB</a> All Rights Reserved. </p>
          </div>
         
        </div>
      </div>
    </div>
  </footer>

templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top">
    <div class="container">
      <a class="navbar-brand" href="https://no31VC7Jjjy1.net">
        <img src="{% static 'assets/uploads/logo/logo.png' %}" alt="PTC">
      </a>
      <button class="navbar-toggler p-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="far fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/' %} active {% endif %}" href="{% url 'home:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/about/' %} active {% endif %}" href="{% url 'home:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/plans/' %} active {% endif %}" href="{% url 'home:plan' %}">Plan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/faq/' %} active {% endif %}" href="{% url 'home:faq' %}">FAQ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/blog/' %} active {% endif %}" href="{% url 'home:blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/contact/' %} active {% endif %}" href="{% url 'home:contact' %}">Contact</a>
          </li>
        </ul>
      </div>
      <!-- navbar text -->
      <span class="navbar-text">
        <!-- notification panel -->
         {% if user.is_authenticated %}
         <a href="{% url 'account:logout' %}" class="btn-custom">
          <i class="fal fa-sign-in"></i>
          <span class="d-none d-sm-inline">Sign Out</span>
        </a>
         {% else %}
        <a href="{% url 'account:login' %}" class="btn-custom">
          <i class="fal fa-sign-in"></i>
          <span class="d-none d-sm-inline">Sign In</span>
        </a>
        <a href="{% url 'account:register' %}" class="btn-custom" style="margin-left: 10px;">
          <i class="fal fa-sign-in"></i>
          <span class="d-none d-sm-inline">Register</span>
        </a>
        {% endif %}
      </span>
    </div>
  </nav>